services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-cli
    restart: unless-stopped
    environment:
      - MODE=[json-rpc | native | normal]
    ports:
      - 8080:8080
    volumes:
      - ./config:/home/.local/share/signal-cli