services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      # if you want Uptime Kuma to monitor the local containers, uncomment the next line to expose the Docker daemon:
      #- /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001