services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./:/etc/letsencrypt
      - ./:/var/lib/letsencrypt
      - ./:/var/log/letsencrypt