services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=PLEXUSER-PUID
      - PGID=PLEXUSER-PGID
      - VERSION=latest
    volumes:
      - /dev/shm:/transcode
      - /etc/localtime:/etc/localtime:ro
      - /opt/plex/database:/config
      - /[path to]/multimedia:/multimedia
    restart: unless-stopped