detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

mqtt:
  enabled: false

go2rtc:
  streams:
    mjpeg_cam1: "ffmpeg:http://[motioneyecamera]:9081#video=h264#hardware"
    mjpeg_cam2: "ffmpeg:http://[motioneyecamera]:9082#video=h264#hardware"

cameras:
  CAMERA-01: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam1
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 10

  CAMERA-02: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam2
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 10
version: 0.15-0